kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
#name: mycluster
networking:
  disableDefaultCNI: false
nodes:
  - role: control-plane
  - role: worker
  - role: worker
kubeadmConfigPatches:
  - |
    kind: KubeProxyConfiguration
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    mode: "ipvs"
    ipvs:
      strictARP: true
  - |
    kind: KubeletConfiguration
    cgroupDriver: systemd